baseURL = 'https://imi-lab.net/'
languageCode = 'en-us'
title = 'IMI LAB'
theme = 'ananke'

disableKinds = ["RSS", "taxonomy", "term"]

[params]
  description = "Art of the Possible in SCM"
  background_color_class = "bg-black"
