baseURL = 'https://imi-lab.net/'
languageCode = 'en-us'
title = 'IMI LAB'
theme = 'ananke'

# Core site settings
disableKinds = ["RSS", "taxonomy", "term"]

[params]
  description = "Art of the Possible in SCM"
  background_color_class = "bg-black"
  recent_posts_number = 5
  # Ensure these are the only lines under [params]
