baseURL = 'https://imi-lab.net/'
languageCode = 'en-us'
title = 'IMI LAB'
theme = 'ananke'

# Force Hugo to only produce HTML
[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML"]

[params]
  description = "Art of the Possible in SCM"
   recent_posts_number = 5
